<?php
	function getPageName($currentURL = ''){
		$currentFile = ($currentURL == '') ? $_SERVER["PHP_SELF"] : $currentURL;
		$parts = Explode('/', $currentFile);
		$realurl = Explode('?', $parts[count($parts)-1]);
		return $realurl[0];
	}
	
	function getCurrentPageData($pageLink, $pageURL){
		$pageQuery = "SELECT m.* FROM tmodule m WHERE m.module_pageurl = '$pageURL'";
		if ($pageResult = $pageLink->query($pageQuery)){
			if ($pageResult->num_rows > 0){
				$pageRow = $pageResult->fetch_row();
				$pageData = array(
					'id' => $pageRow[0],
					'name' => $pageRow[1],
					'category' => $pageRow[2],
					'description' => $pageRow[3],
					'pageurl' => $pageRow[4],
					'issub' => $pageRow[5],
					'hascrud' => $pageRow[6],
				);
				$pageResult->free();
				return $pageData;
			}
		}
		else{
			printf("Errormessage: %s\n", $pageLink->error);
		}
	}
	
	function setAccessSession($accessLink, $accessLevel){
		$accessData = array();
		$accessQuery = "SELECT m.module_id, a.access_create, a.access_read, a.access_update, a.access_delete
							 FROM tmodule m
							 LEFT JOIN tlevel_access a ON a.module_id = m.module_id
							 WHERE a.level_id = '$accessLevel'
							";
		if ($accessResult = $accessLink->query($accessQuery)){
			if ($accessResult->num_rows > 0){
				while ($accessRow = $accessResult->fetch_assoc()){
					$accessData[$accessRow['module_id']] = array(
						'create' =>$accessRow['access_create'],
						'read' =>$accessRow['access_read'],
						'update' =>$accessRow['access_update'],
						'delete' =>$accessRow['access_delete'],
					);
				}
				$accessResult->free();
			}
		}
		$_SESSION['access'] = $accessData;
	}
	
	function addLog($mysqli_link, $user_id, $log_name, $log_reference, $log_action){
		//INSERT ACTIVITY LOG
		$log_date = date("Y-m-d H:i:s");
		$log_query = "INSERT INTO tlog (log_name, log_reference, log_action, log_date, user_id) VALUES 
								  ('$log_name', '$log_reference', '$log_action', '$log_date','$user_id');";
		if (!$log_result = $mysqli_link->query($log_query)){
			printf("Errormessage: %s\n", $mysqli_link->error);
		}
	}
	
	function autoGenerateID($autoLink, $autoStr, $autoTable, $autoField, $autoZero){
		$autoGenerated = $autoStr;
		
		$autoLen = strlen($autoStr);	
		$autoCtr = 0;
		$autoQuery = "SELECT max($autoField) as maxid FROM $autoTable WHERE SUBSTRING($autoField,1,$autoLen)='$autoStr'";
		if ($autoResult = $autoLink->query($autoQuery)){
			if ($autoResult->num_rows > 0){
				while ($autoRow = $autoResult->fetch_assoc()){
					$autoCtr = intval(substr($autoRow['maxid'],$autoLen,$autoZero)) + 1;
				}						
			}
			$autoGenerated = $autoStr . str_pad($autoCtr, $autoZero, "0", STR_PAD_LEFT);		
			return $autoGenerated;
		}
		else{
			return printf("Errormessage: %s\n", $autoLink->error);
		}
	}
	
	function getIconName($throwed_name){
		$iconName = '';
		switch (strtolower($throwed_name)) {
			case "utama":
				$iconName = 'dashboard';
				break;
			case "utility":
				$iconName = 'wrench';
				break;
			case "master":
				$iconName = 'edit';
				break;
			case "transaksi":
				$iconName = 'laptop';
				break;
		}
		return $iconName;
	}
?>