<?php
	function getPageName(){
		$currentFile = $_SERVER["PHP_SELF"];
		$parts = Explode('/', $currentFile);
		$realurl = Explode('?', $parts[count($parts)-1]);
		return $realurl[0];
	}
	
	function addLog($mysqli_link, $user_id, $log_name, $log_reference, $log_action){
		//INSERT ACTIVITY LOG
		$log_date = date("Y-m-d H:i:s");
		$log_query = "INSERT INTO tlog (log_name, log_reference, log_action, log_date, user_id) VALUES 
								  ('$log_name', '$log_reference', '$log_action', '$log_date','$user_id');";
		if (!$log_result = $mysqli_link->query($log_query)){
			printf("Errormessage: %s\n", $mysqli_link->error);
		}
	}
	
	function autoGenerateID($autoLink, $autoStr, $autoTable, $autoField, $autoZero){
		$autoGenerated = $autoStr;
		
		$autoLen = strlen($autoStr);	
		$autoCtr = 0;
		$autoQuery = "SELECT max($autoField) as maxid FROM $autoTable WHERE SUBSTRING($autoField,1,$autoLen)='$autoStr'";
		if ($autoResult = $autoLink->query($autoQuery)){
			if ($autoResult->num_rows > 0){
				while ($autoRow = $autoResult->fetch_assoc()){
					$autoCtr = intval(substr($autoRow['maxid'],$autoLen,$autoZero)) + 1;
				}						
			}
			$autoGenerated = $autoStr . str_pad($autoCtr, $autoZero, "0", STR_PAD_LEFT);		
			return $autoGenerated;
		}
		else{
			return printf("Errormessage: %s\n", $autoLink->error);
		}
	}
	
	function getIconName($throwed_name){
		$iconName = '';
		switch ($throwed_name) {
			case "Utama":
				$iconName = 'dashboard';
				break;
			case "Utility":
				$iconName = 'wrench';
				break;
		}
		return $iconName;
	}
?>